/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplos.figurasABS;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author delcenjo
 */
public class GUIFiguras extends javax.swing.JFrame {

    /**
     * Creates new form GUIFiguras
     */
    public GUIFiguras() {
        initComponents();
        setFrame();
    }
    
    private void setFrame(){
        this.setLocationRelativeTo(null);
        this.setTitle("Figuras Geométricas");
        this.setMinimumSize(new Dimension(400, 200));
        this.setPreferredSize(new Dimension(400, 200));
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jButton1.setText("Circulo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        jButton2.setText("Rectangulo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);

        jButton3.setText("Cuadrado");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);

        jButton4.setText("Triangulo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double radio = Double.parseDouble(JOptionPane.showInputDialog("Introduce radio: "));
        Circulo circulo = new Circulo(radio, new Punto(0,0));
        calcularAreaFigura(circulo);
        calcularPerimetroFigura(circulo);
        pintarFigura(circulo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double lado1 = Double.parseDouble(JOptionPane.showInputDialog("Introduce lado1: "));
        double lado2 = Double.parseDouble(JOptionPane.showInputDialog("Introduce lado2: "));
        Rectangulo rectangulo = new Rectangulo(lado1, lado2, new Punto(0,0));
        calcularAreaFigura(rectangulo);
        calcularPerimetroFigura(rectangulo);
        calcularDiagonal(rectangulo);
        pintarFigura(rectangulo);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        double lado1 = Double.parseDouble(JOptionPane.showInputDialog("Introduce lado1: "));
        double lado2 = Double.parseDouble(JOptionPane.showInputDialog("Introduce lado2: "));
        Cuadrado cuadrado = new Cuadrado(lado1, lado2, new Punto(0,0));
        calcularAreaFigura(cuadrado);
        calcularPerimetroFigura(cuadrado);
        calcularDiagonal(cuadrado);
        pintarFigura(cuadrado);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        double base = Double.parseDouble(JOptionPane.showInputDialog("Introduce base: "));
        double altura = Double.parseDouble(JOptionPane.showInputDialog("Introduce altura: "));
        Triangulo triangulo = new Triangulo(base, altura, new Punto(0,0));
        calcularAreaFigura(triangulo);
        calcularPerimetroFigura(triangulo);
        pintarFigura(triangulo);
    }//GEN-LAST:event_jButton4ActionPerformed
    
    public void calcularAreaFigura(Figura figura){
        System.out.println(figura.calcularArea());
    }
    
    public void calcularPerimetroFigura(Figura figura){
        System.out.println(figura.calcularPerimetro());
    }
    
    public void pintarFigura(Figura figura){
        figura.dibujarFigura();
    }
    
    public void calcularDiagonal(Cuadrilatero cuadrilatero){
        System.out.println(cuadrilatero.calcularDiagonal());
    }
    
    public void mostrarInfoFigura(Figura figura){
        System.out.println(figura);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFiguras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
